chatty_back/diary/urls.py
from django.urls import path
from . import views

app_name = "diary"
urlpatterns = [
    path('main/', views.Diary_Main.as_view(), name='main diaries module'),
    path('startchat/', views.Startchat.as_view(), name='start chat'),
    path('chat/<int:diary_id>/', views.Chat.as_view(), name='chat'),
    path('feeling/<int:diary_id>/', views.Feeling.as_view(), name='feeling'), 
    path('detail/<int:diary_id>/', views.DiaryDetail.as_view(), name='diary detail'),
    path('calendar/', views.ThisMonth_Calendar.as_view(), name='this month calendar'),
    path('calendar/<int:month>/', views.OtherMonth_Calendar.as_view(), name='other month calendar'),
    path('question/', views.Question.as_view(), name='add question'),
    path('question/list/', views.QuestionList.as_view(), name='list question'),

    path('question_set/', views.CreateQuestionSet.as_view(), name='question_set'), # 임시 url
]

chatty_back/partners/urls.py
from django.urls import path
from . import views

app_name = "partners"
urlpatterns = [
    path('main/', views.Partner_Main.as_view(), name='main partner module'),
    path('partner/', views.Partner.as_view(), name='create partner'),
    path('partner/<int:partner_id>/', views.DeletePartner.as_view(), name='delete partner'),
    path('profile/<int:partner_id>/', views.PartnerProfile.as_view(), name='get partner profile, modify partner profile'),
    path('mypartner/',views.PartnerProfile_setting.as_view(), name='partner_profile_setting'),
    path('mypartner/<int:partner_id>/', views.SetPartner.as_view(), name='set partner'),
]

chatty_back/users/urls.py
from django.urls import path

from chatty_back.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("chatty_back.users.urls", namespace="users"),
    ),

    path(
        "chatty_users/",
        include("chatty_back.chatty_users.urls", namespace="chatty_users"),
    ),

    path(
        "diary/",
        include("chatty_back.diary.urls", namespace="diary"),
    ),

    path(
        "partners/",
        include("chatty_back.partners.urls", namespace="partnsers"),
    ),

    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

chatty_back/chatty_users/views.py
from django.utils.decorators import method_decorator
from django.utils.crypto import get_random_string
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . import models, serializers
from chatty_back.diary.views import check_user



class NewUser(APIView):

    def post(self, request, format=None):

        request_unique_user_id = request.META.get('HTTP_HASH', None)
        
        try:
            request_user = models.ChattyUser.objects.get(unique_user_id=request_unique_user_id)
            return Response(status=status.HTTP_403_FORBIDDEN)
        except models.ChattyUser.DoesNotExist:

            new_unique_user_id = get_random_string(length=40)

            try:
                not_unique_user_hash = models.ChattyUser.objects.get(unique_user_id=new_unique_user_id)
                return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
            except models.ChattyUser.DoesNotExist:
                serializer = serializers.NewUserSerializer(data=request.data)

                if serializer.is_valid():

                    serializer.save(unique_user_id=new_unique_user_id)

                    return Response(data=serializer.data, status=status.HTTP_201_CREATED)
                
                else:

                    return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Main(APIView):

    """ Main """

    @method_decorator(check_user())
    def get(self, request, user, format=None):
        
        serializer = serializers.MainSerializer(user)

        return Response(data=serializer.data, status=status.HTTP_200_OK)


class PartnerList(APIView):

    @method_decorator(check_user())
    def get(self, request, user, format=None):

        serializer = serializers.PartnerListSerializer(user)

        return Response(data=serializer.data, status=status.HTTP_200_OK)

chatty_back/diary/views.py
from django.utils.decorators import method_decorator
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from chatty_back.chatty_users import models as chattyuser_models
from chatty_back.partners import models as partners_models
from . import models, serializers
import datetime 
import requests # 날씨 API에 사용
import json # 날씨 API에 사용


# request 유저가 회원가입이 되어 있는 유저인지 확인하는 함수
def check_user():
    def decorator(func):
        def wrapper(request, *args, **kwargs):

            request_unique_user_id = request.META.get('HTTP_HASH', None)

            try:
                user = chattyuser_models.ChattyUser.objects.get(unique_user_id=request_unique_user_id)
                return func(request, user, *args, **kwargs)

            except chattyuser_models.ChattyUser.DoesNotExist:
                raise Exception("Needs login")   

        return wrapper
    return decorator


# 처음 일기를 작성할 때 자동으로 날씨 정보를 가져오는 함수
def get_weather(self, city):

    api_address = 'http://api.openweathermap.org/data/2.5/weather?appid=63321e5f0464f10f168bb0d73ad4512b&q='

    url = api_address + city
    
    response = requests.get(url)
    
    response_json = response.json()

    weather = response_json['weather'][0]['main']

    return weather


class Startchat(APIView):

    """ 채팅을 처음 시작했을 때 """

    @method_decorator(check_user())
    def post(self, request, user, format=None):

        request_day = timezone.localtime().day

        #try: 
            #today_diary = models.Single_diary.objects.get(creator=user, created_at__day=request_day)
            #return Response(status=status.HTTP_401_UNAUTHORIZED) # 이미 당일 작성한 일기가 있을 경우, 재작성 불가능
        #except models.Single_diary.DoesNotExist:
        weather = get_weather(self, 'Seoul')
        
        question_set = models.Question_set.objects.order_by("?").first() # 테스트 -> 이후에 랜덤 추출로 변경 필요

        new_diary = models.Single_diary.objects.create(creator=user, question_set=question_set, partner=user.partner, weather=weather)

        new_diary.save()

        serializer = serializers.StartChatSerializer(new_diary)

        return Response(data=serializer.data, status=status.HTTP_201_CREATED)
            

class Chat(APIView):

    """ 처음 채팅 시작 이후 채팅 """

    @method_decorator(check_user())
    def post(self, requset, user, diary_id, format=None):
       
        try:
            diary = models.Single_diary.objects.get(creator=user, id=diary_id)
        except models.Single_diary.DoesNotExist:
            return Response(status=status.HTTP_204_NO_CONTENT)

        current_question = diary.current_question

        if current_question==None:           

            return Response(data=None, status=status.HTTP_404_NOT_FOUND)
        
        else:

            serializer = serializers.AnswerSerializer_store(data=requset.data)

            if serializer.is_valid():
                
                serializer.save(diary=diary, creator=user, question=current_question)

                diary.state = 'ongoing'
                
                diary.save()

                next_question = diary.current_question

                if next_question == None:

                    diary.state = 'complete'

                    diary.save()

                    return Response(None, status=status.HTTP_204_NO_CONTENT)
                
                else:
                    serializer = serializers.QuestionSerializer(next_question)

                    return Response(data=serializer.data, status=status.HTTP_200_OK)
            
            else:
                return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class Feeling(APIView):

    """ feeling """

    @method_decorator(check_user())
    def put(self, request, user, diary_id, format=None):

        try:
            diary = models.Single_diary.objects.get(creator=user, id=diary_id, state='complete')
        except models.Single_diary.DoesNotExist:
            return Response(status=status.HTTP_204_NO_CONTENT)

        serializer = serializers.FeelingSerializer(diary, data=request.data)

        if serializer.is_valid():

            serializer.save()
            
            return Response(data=serializer.data, status=status.HTTP_200_OK)

        else:
            return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DiaryDetail(APIView):

    """ 다이어리 상세보기 """

    @method_decorator(check_user())
    def get(self, request, user, diary_id, format=None):
        
        user_diary = models.Single_diary.objects.get(id=diary_id, creator=user, state='complete')
        
        serializer = serializers.DiaryDetailSerializer(user_diary)

        return Response(data=serializer.data, status=status.HTTP_200_OK)

    
class ThisMonth_Calendar(APIView):

    """ request가 이루어진 달의 달력 """

    @method_decorator(check_user())
    def get(self, request, user, format=None):

        request_month = timezone.localtime().month

        user_diaries = models.Single_diary.objects.filter(
            creator=user, created_at__month=request_month
            )

        serializer = serializers.CalendarSerializer(user_diaries, many=True)

        return Response(data=serializer.data, status=status.HTTP_200_OK)


class OtherMonth_Calendar(APIView):

    """ request가 이루어진 달 외의 달력 """

    @method_decorator(check_user())
    def get(self, request, user, month, format=None):
        
        user_diaries = models.Single_diary.objects.filter(
            creator=user, created_at__month=month
        )

        serializer = serializers.CalendarSerializer(user_diaries, many=True)

        return Response(data=serializer.data, status=status.HTTP_200_OK)


class Question(APIView):

    """ Add Question """

    @method_decorator(check_user())
    def post(self, request, user, format=None):

        serializer = serializers.QuestionSerializer(data=request.data, partial=True)

        if serializer.is_valid():

            serializer.save(creator=user)

            return Response(data=serializer.data, status=status.HTTP_201_CREATED)

        else:

            return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class QuestionList(APIView):

    """ Question List """

    @method_decorator(check_user())
    def get(self, request, user, format=None):

        user_question = models.Question.objects.filter(creator=user)

        serializer = serializers.QuestionSerializer(user_question, many=True)

        return Response(data=serializer.data, status=status.HTTP_200_OK)


class Diary_Main(APIView):

    @method_decorator(check_user())
    def get(self, request, user, format=None):

        user_diaries = models.Single_diary.objects.filter(creator=user, state='complete')

        if user_diaries is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else:

            serializer = serializers.MainDiarySerializer(user_diaries, many=True)

            return Response(data=serializer.data, status=status.HTTP_200_OK)


#임시 API
class CreateQuestionSet(APIView):

    @method_decorator(check_user())
    def post(self, request, user, format=None):

        serializer = serializers.QS_Serializer(data=request.data)

        if serializer.is_valid():

            serializer.save()

            return Response(data=serializer.data, status=status.HTTP_201_CREATED)

        else:

            return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

chatty_back/partners/views.py
from django.utils.decorators import method_decorator
from rest_framework.views import APIView
from rest_framework.response import Response 
from rest_framework import status
from . import models, serializers
from chatty_back.diary.views import check_user



def get_partner(self, partner_id, creator):

    try:
        found_partner = models.Partner.objects.get(id=partner_id, creator=creator)
        return found_partner
    except models.Partner.DoesNotExist:
        return None


class Partner(APIView):

    @method_decorator(check_user())
    def post(self, request, user, format=None):

        new_partner_name = request.data.get('name', None)
        
        try:
            found_partner = models.Partner.objects.get(name=new_partner_name, creator=user)
            
        except models.Partner.DoesNotExist:
        
            serializer = serializers.CreatePartnerSerializer(data=request.data, partial=True)

            if serializer.is_valid():

                new_partner = serializer.save(creator=user)
                #파트너가 생성된 후, 직전에 생성된 파트너를 함께 일기 쓸 파트너로 선택하기
                user.partner = new_partner

                user.save()

                print(user.partner.name)

                return Response(data=serializer.data, status=status.HTTP_201_CREATED)
                
            else:

                return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        

class PartnerProfile(APIView):

    @method_decorator(check_user())
    def get(self, request, user, partner_id, format=None):

        found_partner = get_partner(self, partner_id, user)

        if found_partner is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else: 

            serializer = serializers.PartnerProfileSerializer(found_partner)

            return Response(data=serializer.data, status=status.HTTP_200_OK)


    @method_decorator(check_user())
    def put(self, request, user, partner_id, format=None):

        found_partner = get_partner(self, partner_id, user)

        if found_partner is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else:

            serializer = serializers.PartnerProfileSerializer(
                found_partner, data=request.data, partial=True)

            if serializer.is_valid():

                serializer.save()

                return Response(data=serializer.data, status=status.HTTP_200_OK)

            else:
                
                return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DeletePartner(APIView):
    
    @method_decorator(check_user())
    def delete(self, request, user, partner_id, format=None):
        
        found_partner = get_partner(self, partner_id, user)

        if found_partner is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else:

            found_partner.delete()

            return Response(status=status.HTTP_204_NO_CONTENT)


class SetPartner(APIView):

    @method_decorator(check_user())
    def put(self, request, user, partner_id, format=None):

        found_partner = get_partner(self, partner_id, user)
        
        if found_partner is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else:

            user.partner = found_partner

            user.save()

            return Response(status=status.HTTP_200_OK)


# Main 화면에 있는 Partner 부분(Main 화면의 module화를 위한 API)
class Partner_Main(APIView):

    @method_decorator(check_user())
    def get(self, request, user, format=None):

        found_partner = user.partner

        if found_partner is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else:

            serializer = serializers.MainPartnerSerializer(found_partner)

            return Response(data=serializer.data, status=status.HTTP_200_OK)


class PartnerProfile_setting(APIView):

    @method_decorator(check_user())
    def get(self, request, user, format=None):

        found_partner = user.partner

        if found_partner is None:

            return Response(status=status.HTTP_404_NOT_FOUND)

        else:

            serializer = serializers.PartnerProfileSerializer(found_partner)

            return Response(data=serializer.data, status=status.HTTP_200_OK)

chatty_back/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

chatty_back/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}chatty_back{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">chatty_back</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 